const LOG_IN = "LOG_IN";
const LOG_IN_ERROR = "LOG_IN_ERROR";
const REGISTER_ERROR = "REGISTER_ERROR"
const LOG_OUT = "LOG_OUT";
const GET_INFO = 'GET_INFO';
const FETCH_TODO_LIST = "FETCH_TODO_LIST";
const ADD_TASK = 'ADD_TASK';
const ADD_EDIT_TASK = 'ADD_TASK_EDIT';
const CANCEL_EDIT_TASK = 'CANCEL_EDIT_TASK';
const EDIT_TASK = 'EDIT_TASK';
const CHANGE_INPUT_EDIT_TASK = "CHANGE_INPUT_EDIT_TASK";
const DELETE_TASK = 'DELETE_TASK';
const DONE_TASK = 'DONE_TASK';
const SUCCESS_ACTION = 'SUCCESS_ACTION'
const ERROR_ACTION = 'ERROR_ACTION'

export {
    LOG_IN,
    LOG_IN_ERROR,
    REGISTER_ERROR,
    LOG_OUT,
    GET_INFO,
    FETCH_TODO_LIST,
    ADD_TASK,
    ADD_EDIT_TASK,
    CANCEL_EDIT_TASK,
    EDIT_TASK,
    CHANGE_INPUT_EDIT_TASK,
    DELETE_TASK,
    DONE_TASK,
    SUCCESS_ACTION,
    ERROR_ACTION,
}