const LOG_IN = "LOG_IN";
const LOG_IN_ERROR = "LOG_IN_ERROR";
const REGISTER_ERROR = "REGISTER_ERROR"
const LOG_OUT = "LOG_OUT";
const GET_INFO = 'GET_INFO'
const FETCH_TODO_LIST = "FETCH_TODO_LIST";
const ADD_TASK = 'ADD_TASK';
const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
const ADD_TASK_ERROR = 'ADD_TASK_ERROR';
const ADD_EDIT_TASK = 'ADD_TASK_EDIT';
const CANCEL_EDIT_TASK = 'CANCEL_EDIT_TASK';
const EDIT_TASK = 'EDIT_TASK';
const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';
const DELETE_TASK = 'DELETE_TASK';
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
const DONE_TASK = 'DONE_TASK'

export {
    LOG_IN,
    LOG_IN_ERROR,
    REGISTER_ERROR,
    LOG_OUT,
    GET_INFO,
    FETCH_TODO_LIST,
    ADD_TASK,
    ADD_TASK_SUCCESS,
    ADD_TASK_ERROR,
    ADD_EDIT_TASK,
    CANCEL_EDIT_TASK,
    EDIT_TASK,
    EDIT_TASK_SUCCESS,
    EDIT_TASK_ERROR,
    DELETE_TASK,
    DELETE_TASK_SUCCESS,
    DELETE_TASK_ERROR,
    DONE_TASK
}